functionsDirectory = "/Users/david/Desktop/rentalbots-site/netlify/functions"
functionsDirectoryOrigin = "config-v1"
plugins = []
headers = []
redirects = []

[build]
publish = "/Users/david/Desktop/rentalbots-site"
publishOrigin = "default"
functions = "/Users/david/Desktop/rentalbots-site/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]